### ISSUE TITLE
Issue parsing XML when com.fasterxml.aalto-xml is in the Maven dependency

### ISSUE THREAD

**Issue by Maatary** [FasterXML/aalto-xml#31]
I'm having trouble with the library com.fasterxml.aalto-xml.

I Have a Project A (Dspace) that do not depend on the library com.fasterxml.aalto-xml.

I developed a library B, that use a library C that depends on com.fasterxml.aalto-xml.

I wonder why when com.fasterxml.aalto-xml gets added as a dependency to A by way of B -> C, A picks up com.fasterxml.aalto-xml to do his usual XML Parsing.
The problem is that, it breaks the application. com.fasterxml.aalto-xml is having trouble to properly parse the XML that comes originally with A. Something is going wrong.

I would like to understand why does it happens. Is there a way to tell A not to use com.fasterxml.aalto-xml but still having B -> C -> com.fasterxml.aalto-xml at work within the A project.

What is particular about those XML parsers? I just don't understand why A would pick up com.fasterxml.aalto-xml to work with it, while it does not have any dependency on it.

I can see that the lib is also an osgi bundle jar, may it has any implication here ?

I mean originally A (Dspace) works without alto and use whatever parser it has, why picking alto now that it is in the dependency ? what mechanism allow that ?

**Comment by Maatary** [comment]
To further simplify the issue and drill down to the problem here is what i Did. 

Project A (Dspace) normaly work and parse XML without issue. It has depencies on several XML library already like: javax.xml.stream.stax-api.1.0-2, etc....
To test, I just add, faster-xml.aalto-xml in the dependency of A, even tho, A is not supposed to use its code. 
However i get an error of paring due to aalto. My conclusion is that A, somehow is using it, i don't understand why. 

Caused by: org.dspace.app.xmlui.wing.WingException: Attempting to merge DRI documents but the source document is not compatable with the feeder document.
	at org.dspace.app.xmlui.wing.AbstractWingTransformer.startElement(AbstractWingTransformer.java:194)
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.cocoon.core.container.spring.avalon.PoolableProxyHandler.invoke(PoolableProxyHandler.java:71)
	at com.sun.proxy.$Proxy29.startElement(Unknown Source)
	at org.apache.cocoon.environment.internal.EnvironmentChanger.startElement(EnvironmentStack.java:140)
	at org.apache.cocoon.components.sax.XMLTeePipe.startElement(XMLTeePipe.java:87)
	at com.fasterxml.aalto.in.XmlScanner.fireSaxStartElement(XmlScanner.java:674)
	at com.fasterxml.aalto.sax.SAXParserImpl.fireStartTag(SAXParserImpl.java:521)
	at com.fasterxml.aalto.sax.SAXParserImpl.fireEvents(SAXParserImpl.java:438)
	at com.fasterxml.aalto.sax.SAXParserImpl.parse(SAXParserImpl.java:370)
	at org.apache.cocoon.core.xml.impl.JaxpSAXParser.parse(JaxpSAXParser.java:196)
	at org.apache.cocoon.core.xml.impl.JaxpSAXParser.parse(JaxpSAXParser.java:204)
	at org.apache.cocoon.components.source.util.SourceUtil.parse(SourceUtil.java:297)
	at org.apache.cocoon.generation.FileGenerator.generate(FileGenerator.java:136)
	... 365 more

I know the problem comes the addition of aalto in the library dependency, because stop working proper as soon as aalto is in it dependency. 

Is aalto done in a way that it takes over xml parsing on the JVM, whenever added to a projecting. Does it has to do with the OSGI jar bundling maybe. 

Any clues please, i am lost.

**Comment by Maatary** [comment]
To further confirm that is comes from it, this is the first part of the error that comes before the "caused by" above: 

at org.apache.cocoon.components.source.util.SourceUtil.handleSAXException(SourceUtil.java:409)
	at org.apache.cocoon.generation.FileGenerator.generate(FileGenerator.java:138)
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.cocoon.core.container.spring.avalon.PoolableProxyHandler.invoke(PoolableProxyHandler.java:71)
	at com.sun.proxy.$Proxy25.generate(Unknown Source)
	at org.apache.cocoon.components.pipeline.impl.AbstractCachingProcessingPipeline.processXMLPipeline(AbstractCachingProcessingPipeline.java:326)
	at org.apache.cocoon.components.pipeline.AbstractProcessingPipeline.process(AbstractProcessingPipeline.java:750)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.cocoon.core.container.spring.avalon.PoolableProxyHandler.invoke(PoolableProxyHandler.java:71)
	at com.sun.proxy.$Proxy24.process(Unknown Source)
	at org.apache.cocoon.components.source.impl.SitemapSource.toSAX(SitemapSource.java:362)
	at org.apache.cocoon.components.source.util.SourceUtil.toSAX(SourceUtil.java:111)
	at org.apache.cocoon.components.source.util.SourceUtil.parse(SourceUtil.java:294)
	at org.apache.cocoon.generation.FileGenerator.generate(FileGenerator.java:136)
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by cowtowncoder** [comment]
Attached information unfortunately does not help at all in figuring out what the problem is, or even that it has anything to do with Aalto. You will have to dig more information before we can help you.
